name: todoapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.21.1
  firebase_auth: 3.7.0
  cloud_firestore: 3.4.6
  google_fonts: 3.0.1
  lottie: 1.4.2
  flutter_screenutil: 5.5.3+2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/lottie/
    - assets/img/

